<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>KONG</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>29</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>1528.9360342236237</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>1156.6605435</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>381.8045008115677</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>1166.2980302934711</CalcMass>
                    <CalcCG>381.8045008115677</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>609.5999999999999</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>1285.0</KnownMass>
                            <Density>7850.0</Density>
                            <Material>Steel</Material>
                            <Name>Bulkhead (combine with threaded rod mass)</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>241.2999999999999</Xb>
                            <CalcMass>707.767835719371</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>2</SerialNo>
                            <OD>95.0744412283798</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>90.718474</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Aluminum Nose Tip</Name>
                            <KnownCG>12.699999999999994</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>12.699999999999994</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                    <BaseDia>158.75</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>152.39999999999998</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>68.0388555</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Upper Body tube (FG)</Name>
                    <KnownCG>44.449999999999996</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>378.91676335911035</CalcMass>
                    <CalcCG>44.449999999999996</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>88.89999999999999</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>4</SerialNo>
                    <OD>158.75</OD>
                    <ID>149.225</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>149.225</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>821.4513632763035</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Up-Mid Coupler</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-152.39999999999998</Xb>
                            <CalcMass>821.4513632763035</CalcMass>
                            <CalcCG>152.39999999999998</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <OD>149.225</OD>
                            <ID>142.875</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>1696.4354638000002</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Avionics Bay</Name>
                            <KnownCG>-50.8</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-50.8</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2884.8474732000004</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Middle Body tube (FG)606.</Name>
                    <KnownCG>609.5999999999999</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>3500.0971130903395</CalcMass>
                    <CalcCG>609.5999999999999</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>1219.1999999999998</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>158.75</OD>
                    <ID>152.4</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>152.4</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <MassObject>
                            <KnownMass>6.369066289239993</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Charge Wells</Name>
                            <KnownCG>203.2</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>203.2</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Ring>
                            <KnownMass>839.3090016083964</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Mid-BoosterCoupler</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-152.39999999999998</Xb>
                            <CalcMass>839.3090016083964</CalcMass>
                            <CalcCG>152.39999999999998</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>152.4</OD>
                            <ID>146.05</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>657.7089365</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Forward Recovery Hardware</Name>
                            <KnownCG>220.98</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>220.98</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>843.6818082000001</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Main Parachute &amp; 2 TD-2s</Name>
                            <KnownCG>101.6</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>708.66</Xb>
                            <CalcMass>708.1747811999028</CalcMass>
                            <CalcCG>101.6</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>3657.6</Dia>
                            <ShroudLineCount>4</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>300.0</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0035</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Braided nylon (3 mm, 1/8 in)</ShroudLineMaterial>
                            <DragCoefficient>0.97</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>563.021528766</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Top of Middle Tube Bulkhead</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>203.2</Xb>
                            <CalcMass>625.4999804971151</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>152.4</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>5406.821050400001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Payload</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>152.39999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>355.59999999999997</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>6.369066289239993</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Charge Wells</Name>
                            <KnownCG>762.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>762.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Streamer>
                            <KnownMass>489.87975960000006</KnownMass>
                            <Density>0.006700000000000001</Density>
                            <Material>Ripstop nylon</Material>
                            <Name>Streamer</Name>
                            <KnownCG>127.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-101.60000000000014</Xb>
                            <CalcMass>518.7086400000001</CalcMass>
                            <CalcCG>127.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>254.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <Width>254.0</Width>
                            <DragCoefficient>0.15</DragCoefficient>
                        </Streamer>
                        <MassObject>
                            <KnownMass>476.2719885</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock cord</Name>
                            <KnownCG>507.9999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>507.9999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>203.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>757.4992579000001</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Aft Recovery Hardware</Name>
                            <KnownCG>-152.39999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-152.39999999999998</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>50.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <LaunchLug>
                            <KnownMass>1.569225530468102</KnownMass>
                            <Density>1850.0</Density>
                            <Material>Fiberglass</Material>
                            <Name>Launch Lug</Name>
                            <KnownCG>15.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>935.1999999999998</Xb>
                            <CalcMass>1.569225530468102</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>3.141592653589793</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>10.0</OD>
                            <ID>8.0</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>2122.8122915999998</KnownMass>
                    <Density>1850.0</Density>
                    <Material>Fiberglass</Material>
                    <Name>Booster Tube (CF)</Name>
                    <KnownCG>419.09999999999997</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>2406.3167652496154</CalcMass>
                    <CalcCG>419.09999999999997</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>838.1999999999999</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>19</SerialNo>
                    <OD>158.75</OD>
                    <ID>152.39999999999998</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>152.39999999999998</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>1531.4384622384466</KnownMass>
                            <Density>1780.0</Density>
                            <Material>Carbon fiber</Material>
                            <Name>Trapezoidal Fins</Name>
                            <KnownCG>181.58201692011897</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>1531.4384622384466</CalcMass>
                            <CalcCG>181.58201692011897</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>20</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>304.79999999999995</RootChord>
                            <TipChord>76.19999999999999</TipChord>
                            <SemiSpan>147.31999999999996</SemiSpan>
                            <SweepDistance>203.2424851882134</SweepDistance>
                            <Thickness>6.35</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>1</TipShapeCode>
                            <TabLength>228.6</TabLength>
                            <TabDepth>25.4</TabDepth>
                            <TabOffset>38.09999999999998</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>560.1185010542065</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Motor Tube</Name>
                            <KnownCG>406.4</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-152.39999999999998</Xb>
                            <CalcMass>560.1185010542065</CalcMass>
                            <CalcCG>406.4</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>812.8</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <OD>104.77499999999999</OD>
                            <ID>98.425</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>98.425</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>178.60199553</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Top of Motor Bulkhead</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>666.75</Xb>
                            <CalcMass>312.7499902485575</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <OD>152.39999999999998</OD>
                            <ID>0.0</ID>
                            <UsageCode>1</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>68.21296083610513</KnownMass>
                            <Density>530.0</Density>
                            <Material>Pine</Material>
                            <Name>Motor Centering Ring 1</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>497.84000000000003</Xb>
                            <CalcMass>68.21296083610513</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>23</SerialNo>
                            <OD>152.39999999999998</OD>
                            <ID>101.6</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>68.21296083610513</KnownMass>
                            <Density>530.0</Density>
                            <Material>Pine</Material>
                            <Name>Motor Centering Ring 2</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>330.2</Xb>
                            <CalcMass>68.21296083610513</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>24</SerialNo>
                            <OD>152.39999999999998</OD>
                            <ID>101.6</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <BodyTube>
                            <KnownMass>453.59237</KnownMass>
                            <Density>1190.0</Density>
                            <Material>Acrylic</Material>
                            <Name>Fin Support Structure + Transition to Boat Tail (?)</Name>
                            <KnownCG>152.39999999999998</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>86.54452027950498</CalcMass>
                            <CalcCG>152.39999999999998</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>304.79999999999995</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>25</SerialNo>
                            <OD>152.39999999999998</OD>
                            <ID>151.39999999999998</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>151.39999999999998</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <LaunchLug>
                            <KnownMass>1.509849429315255</KnownMass>
                            <Density>1780.0</Density>
                            <Material>Carbon fiber</Material>
                            <Name>Launch Lug</Name>
                            <KnownCG>15.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>711.1999999999998</Xb>
                            <CalcMass>1.509849429315255</CalcMass>
                            <CalcCG>15.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>3.141592653589793</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>30.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>26</SerialNo>
                            <OD>10.0</OD>
                            <ID>8.0</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>730.0002198249999</KnownMass>
                    <Density>1780.0</Density>
                    <Material>Carbon fiber</Material>
                    <Name>Boat Tail</Name>
                    <KnownCG>72.6555268868752</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>372.21926023328894</CalcMass>
                    <CalcCG>72.6555268868752</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>152.39999999999998</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>27</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>3.175</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>127.74968351680666</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Thrust Plate</Name>
                            <KnownCG>6.35</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-12.7</Xb>
                            <CalcMass>127.74968351680666</CalcMass>
                            <CalcCG>6.35</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>12.7</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>28</SerialNo>
                            <OD>120.64999999999999</OD>
                            <ID>99.06</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>63.87484175840333</KnownMass>
                            <Density>2700.0</Density>
                            <Material>Aluminum</Material>
                            <Name>Motor Retainer</Name>
                            <KnownCG>3.175</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-19.049999999999997</Xb>
                            <CalcMass>63.87484175840333</CalcMass>
                            <CalcCG>3.175</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.35</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>29</SerialNo>
                            <OD>120.64999999999999</OD>
                            <ID>99.06</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                    <FrontShoulderLen>63.5</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>152.39999999999998</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>158.75</FrontDia>
                    <RearDia>120.64999999999999</RearDia>
                </Transition>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>